### PR TITLE
👦 Human went extinct

### PR DESCRIPTION
**Pull request by akihikodaki**
Human went extinct as far as I know.

### CODE REVIEW

**Comment by miyaoka** [comment]
before|after
---|---
b|a

brilliant work!! 💀

**Review by akihikodaki — COMMENTED** [review]
Awesome! Why not use Wikibase APIs?
https://www.wikidata.org/w/api.php

**Review by akihikodaki — COMMENTED** [review]
Rebase?

**Comment by miyaoka** [comment]
Thank you. I'll try to use Wikibase API.

**Comment by miyaoka** [comment]
@akihikodaki Hmm... It's hard for me.
Can you implement it?

**Comment by akihikodaki** [comment]
@miyaoka Take it easy! I'll show you how to implement. Meow meow meow meow meow...

**Comment by akihikodaki** [comment]
81d766a391aeac5ae672f617021340ce744667bc: That's it. Doesn't it look easy?

**Comment by akihikodaki** [comment]
By the way, it seems possible to fetch the sitelinks on client side, so it does. It will benefit when the list of the sitelinks gets updated.

**Comment by miyaoka** [comment]
I understand that user will get the latest list info when user starts for the first time.
However, the local storage never update after that.
That's need an update button or something. I don't want add that...

So I think it would be better to get it at build.  
They are not to be updated so much.

**Comment by akihikodaki** [comment]
It actually does once in every session. The _session_ is the period after a japarized Wikipedia page gets shown and before the extension gets disabled or another startup of the extension occurs.

Actually it may sound so frequent, but it's not so different from making a HTTP request of the article every time when the user wants to see it. (and it is far more smaller than articles; e.g. 3KB API response v.s. 138KB Human article)

**Comment by akihikodaki** [comment]
8292398076b2910b1b4c508f0d37503569518e6c: It now functions even offline once a cache has made. Previously, startups and extension toggling have removed the cache, but now it sets false to valid flag instead, which allows to fallback to use the invalidated cache when fetching failed.

**Comment by miyaoka** [comment]
Thank you, I'll check it.

**Comment by miyaoka** [comment]
Sorry for my late reply.

I consider that it's not good to use local storage for this feature.
Because, that URI list are not user specific data. 
Also, once the data is stored on the user local, it will be difficult for us to maintain.

Anyway, this is just a function to replace view, so I'd like to release it as soon as possible. (Because it depends on the remaining story. :p)

So I hope to process it with fixed URI without fetching for now.

**Comment by akihikodaki** [comment]
> Because, that URI list are not user specific data.

Is there any reason it shouldn't have data other than user specific one?

> Also, once the data is stored on the user local, it will be difficult for us to maintain.

I don't think so. Chrome provides APIs to detect updates of extension. The data don't have to be preserved after updates, so we can simply remove or ignore if the data becomes unnecessary.

> Anyway, this is just a function to replace view, so I'd like to release it as soon as possible. (Because it depends on the remaining story. :p)

That makes sense.

**Pull request closed without merging**
